version: '3.8'

services:
  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 2


    volumes:
      - kafka-data:/var/lib/kafka/data

  fastapi-service:
    build:
      context: animals_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  reader-service:
    build:
      context: animals_manager
      dockerfile: Dockerfile
    depends_on:
      - kafka
    deploy:
      replicas: 2

volumes:
  kafka-data:

